# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lockin < Formula
  desc "Full-screen terminal focus timer"
  homepage "https://github.com/jeffnv/lockin"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jeffnv/lockin/releases/download/v0.1.0/lockin_0.1.0_darwin_amd64.tar.gz"
      sha256 "9102def21af7886d366d6ee9bb38c2d39a353ac40cbfa78eb39a21be577b2750"

      define_method(:install) do
        bin.install "lockin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jeffnv/lockin/releases/download/v0.1.0/lockin_0.1.0_darwin_arm64.tar.gz"
      sha256 "0a514936e349c8bea4a14b3a31985a6d77209937fb619345392382ff507bcb50"

      define_method(:install) do
        bin.install "lockin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jeffnv/lockin/releases/download/v0.1.0/lockin_0.1.0_linux_amd64.tar.gz"
      sha256 "fdc98c2461ebd71df2633028cccb1dd7be6658cbf5f7cff050f6cdb46b8f224b"
      define_method(:install) do
        bin.install "lockin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jeffnv/lockin/releases/download/v0.1.0/lockin_0.1.0_linux_arm64.tar.gz"
      sha256 "0a7ce6f43d90f819af0761ca82d9eae65f6dffa824445fa94a126ab9cc18f6bc"
      define_method(:install) do
        bin.install "lockin"
      end
    end
  end
end
