# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lockin < Formula
  desc "Full-screen terminal focus timer"
  homepage "https://github.com/jeffnv/lockin"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jeffnv/lockin/releases/download/v0.1.0/lockin_0.1.0_darwin_amd64.tar.gz"
      sha256 "b7893b43ce30ba6180284ba8734a0fb212a5020c4cf7f75fb69474c2a5908ac2"

      define_method(:install) do
        bin.install "lockin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jeffnv/lockin/releases/download/v0.1.0/lockin_0.1.0_darwin_arm64.tar.gz"
      sha256 "ce1e808e13ed950d75a7ab1610bf422de1e2e6808f0ae1e63d604fc003c1df3c"

      define_method(:install) do
        bin.install "lockin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jeffnv/lockin/releases/download/v0.1.0/lockin_0.1.0_linux_amd64.tar.gz"
      sha256 "7f4ccf757fecacc65311c7e1dc4056302d318a0f3cd662837530ec9130be420c"
      define_method(:install) do
        bin.install "lockin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jeffnv/lockin/releases/download/v0.1.0/lockin_0.1.0_linux_arm64.tar.gz"
      sha256 "f69a0cefd21c733367c1416dc2feb0aec84cb48cbfea88a9f3b0f294641d51f4"
      define_method(:install) do
        bin.install "lockin"
      end
    end
  end
end
