# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Lockin < Formula
  desc "Full-screen terminal focus timer"
  homepage "https://github.com/jeffnv/lockin"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/jeffnv/lockin/releases/download/v0.1.0/lockin_0.1.0_darwin_amd64.tar.gz"
      sha256 "7182bb3e5fd5f63b80a66c9d7cc58322077b2744d240b41ebf6a482c7f9aa37b"

      define_method(:install) do
        bin.install "lockin"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/jeffnv/lockin/releases/download/v0.1.0/lockin_0.1.0_darwin_arm64.tar.gz"
      sha256 "5ea809b01a2c2c92a2c0c8961cb7d8d254185fd128aa0bc2b367db78edaecd29"

      define_method(:install) do
        bin.install "lockin"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/jeffnv/lockin/releases/download/v0.1.0/lockin_0.1.0_linux_amd64.tar.gz"
      sha256 "dfdb8cb835e7e4e621d5a5c38744fa4ccf8871f5555d1f95b6e777322d9874f2"
      define_method(:install) do
        bin.install "lockin"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/jeffnv/lockin/releases/download/v0.1.0/lockin_0.1.0_linux_arm64.tar.gz"
      sha256 "2a7e1585189f5299bfa2d4380d232ae8bc562e5626fe2f5d72b5b014824b07bf"
      define_method(:install) do
        bin.install "lockin"
      end
    end
  end
end
